module.exports = {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Hiskywin Full Zip Running Shirts',
      category: 'Shirts',
      image: 'pexels-01.jpg',
      price: 59,
      brand: 'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet, assumenda? Rem, consectetur quod. Voluptatem, aliquid quam eum',
    },
    {
      _id: '222222222222222222222222',
      name: 'Nike Full-Zip Hoodie',
      category: 'Shirts',
      image: 'pexels-02.jpg',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 51,
      countInStock: 0,
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet, assumenda? Rem, consectetur quod. Voluptatem, aliquid quam eum Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet, assumenda? Rem, consectetur quod. Voluptatem, aliquid quam eum',
    },
    {
      _id: '333333333333333333333333',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: 'pexels-03.jpg',
      price: 59,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
      countInStock: 6,
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet, assumenda? Rem, consectetur quod. Voluptatem, aliquid quam eum',
    },
    {
      _id: '444444444444444444444444',
      name: 'Under Armour Mens',
      category: 'Pants',
      image: 'pexels-04.jpg',
      price: 90,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet, assumenda? Rem, consectetur quod. Voluptatem, aliquid quam eum',
    },
    {
      _id: '555555555555555555555555',
      name: 'Champion Mens Jogger',
      category: 'Pants',
      image: 'product-1.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet, assumenda? Rem, consectetur quod. Voluptatem, aliquid quam eum',
    },
    {
      _id: '666666666666666666666666',
      name: 'Pants Long Multi-Pockets',
      category: 'Pants',
      image: 'product-2.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
      desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet, assumenda? Rem, consectetur quod. Voluptatem, aliquid quam eum',
    },
  ],
};
